# -*- Perl -*-

use strict;
use warnings;

use lib 'cgi-perl/lib/perl5';

use Test::More tests => 4;
use Test::Differences;
use XML::Twig;

BEGIN { use_ok('infix2pharmml') }; # TEST 1

sub i2p {
    my $in=shift;
    my $xml=infix2pharmml::xmlify($in);
    my $twig=XML::Twig->new( pretty_print => 'indented'); 
    $twig->parse($xml);
    my $xml_indented=$twig->sprint;
    return $xml_indented;
}

my $s;
$infix2pharmml::fullmodel=1;



$s="par v_init=10, a=1;";
eq_or_diff(i2p($s),
q(
<?xml version="1.0" encoding="UTF-8"?>
<PharmML implementedBy="http://infix2pharmml.sourceforge.net" writtenVersion="0.3" xmlns="http://www.pharmml.org/2013/03/PharmML" xmlns:ct="http://www.pharmml.org/2013/03/CommonTypes" xmlns:ds="http://www.pharmml.org/2013/08/Dataset" xmlns:math="http://www.pharmml.org/2013/03/Maths" xmlns:mdef="http://www.pharmml.org/2013/03/ModelDefinition" xmlns:mml="http://www.pharmml.org/2013/03/PharmML" xmlns:mstep="http://www.pharmml.org/2013/03/ModellingSteps" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pharmml.org/2013/03/PharmML http://www.pharmml.org/2013/03/PharmML">
  <ct:Name>Anonymous - FIXME</ct:Name>
  <ct:Description>Translation of par v_init=10, a=1; generated by infix2pharmml on Tue Nov 25 15:24:11 2014</ct:Description>
  <!-- Translation of: -->
  <!-- par v_init=10, a=1; -->
  <IndependentVariable symbId="t"/>
  <!-- Insert FunctionDefinition here -->
  <ModelDefinition xmlns="http://www.pharmml.org/2013/03/ModelDefinition">
    <ParameterModel blkId="p">
      <SimpleParameter symbId="a">
        <ct:Assign>
          <math:Equation>
            <ct:Real>1</ct:Real>
          </math:Equation>
        </ct:Assign>
      </SimpleParameter>
      <SimpleParameter symbId="v_init">
        <ct:Assign>
          <math:Equation>
            <ct:Real>10</ct:Real>
          </math:Equation>
        </ct:Assign>
      </SimpleParameter>
    </ParameterModel>
    <!-- STRUCTURAL MODEL -->
    <StructuralModel blkId="sm"></StructuralModel>
  </ModelDefinition>
</PharmML>
),$s);





$s="A:=1 {A constant};";
eq_or_diff(i2p($s),
q(
<?xml version="1.0" encoding="UTF-8"?>
<PharmML implementedBy="http://infix2pharmml.sourceforge.net" writtenVersion="0.3" xmlns="http://www.pharmml.org/2013/03/PharmML" xmlns:ct="http://www.pharmml.org/2013/03/CommonTypes" xmlns:ds="http://www.pharmml.org/2013/08/Dataset" xmlns:math="http://www.pharmml.org/2013/03/Maths" xmlns:mdef="http://www.pharmml.org/2013/03/ModelDefinition" xmlns:mml="http://www.pharmml.org/2013/03/PharmML" xmlns:mstep="http://www.pharmml.org/2013/03/ModellingSteps" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pharmml.org/2013/03/PharmML http://www.pharmml.org/2013/03/PharmML">
  <ct:Name>Anonymous - FIXME</ct:Name>
  <ct:Description>Translation of A:=1 {A constant}; generated by infix2pharmml on Tue Nov 25 15:25:42 2014</ct:Description>
  <!-- Translation of: -->
  <!-- A:=1 {A constant}; -->
  <IndependentVariable symbId="t"/>
  <!-- Insert FunctionDefinition here -->
  <ModelDefinition xmlns="http://www.pharmml.org/2013/03/ModelDefinition">
    <ParameterModel blkId="p"></ParameterModel>
    <!-- STRUCTURAL MODEL -->
    <StructuralModel blkId="sm">
      <!-- A (Variable) -->
      <ct:Variable symbId="A" symbolType="real">
        <ct:Description>A constant</ct:Description>
        <ct:Assign>
          <math:Equation>
            <ct:Real>1</ct:Real>
          </math:Equation>
        </ct:Assign>
      </ct:Variable>
    </StructuralModel>
  </ModelDefinition>
</PharmML>
),$s);




$s="diff(A1,t)=-Cl*A1/V1+Q*(A2/V2-A1/V1); diff(A2,t)=-Q*(A2/V2-A1/V1); C1:=A1/V1";
eq_or_diff(i2p($s),
q(<?xml version="1.0" encoding="UTF-8"?>
<PharmML implementedBy="http://infix2pharmml.sourceforge.net" writtenVersion="0.3" xmlns="http://www.pharmml.org/2013/03/PharmML" xmlns:ct="http://www.pharmml.org/2013/03/CommonTypes" xmlns:ds="http://www.pharmml.org/2013/08/Dataset" xmlns:math="http://www.pharmml.org/2013/03/Maths" xmlns:mdef="http://www.pharmml.org/2013/03/ModelDefinition" xmlns:mml="http://www.pharmml.org/2013/03/PharmML" xmlns:mstep="http://www.pharmml.org/2013/03/ModellingSteps" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pharmml.org/2013/03/PharmML http://www.pharmml.org/2013/03/PharmML">
  <ct:Name>Anonymous - FIXME</ct:Name>
  <ct:Description>Translation of diff(A1,t)=-Cl*A1/V1+Q*(A2/V2-A1/V1); diff(A2,t)=-Q*(A2/V2-A1/V1); C1:=A1/V1 generated by infix2pharmml on Tue Nov 25 15:22:39 2014</ct:Description>
  <!-- Translation of: -->
  <!-- diff(A1,t)=-Cl*A1/V1+Q*(A2/V2-A1/V1); diff(A2,t)=-Q*(A2/V2-A1/V1); C1:=A1/V1 -->
  <IndependentVariable symbId="t"/>
  <!-- Insert FunctionDefinition here -->
  <ModelDefinition xmlns="http://www.pharmml.org/2013/03/ModelDefinition">
    <ParameterModel blkId="p">
      <SimpleParameter symbId="Cl"/>
      <SimpleParameter symbId="V2"/>
      <SimpleParameter symbId="A1_init"/>
      <SimpleParameter symbId="Q"/>
      <SimpleParameter symbId="A2_init"/>
      <SimpleParameter symbId="V1"/>
    </ParameterModel>
    <!-- STRUCTURAL MODEL -->
    <StructuralModel blkId="sm">
      <!-- A1' (ODE) -->
      <ct:DerivativeVariable symbId="A1" symbolType="real">
        <ct:Assign>
          <math:Equation>
            <math:Binop op="plus">
              <math:Binop op="divide">
                <math:Binop op="times">
                  <math:Uniop op="minus">
                    <ct:SymbRef blkIdRef="p" symbIdRef="Cl"/>
                  </math:Uniop>
                  <ct:SymbRef symbIdRef="A1"/>
                </math:Binop>
                <ct:SymbRef blkIdRef="p" symbIdRef="V1"/>
              </math:Binop>
              <math:Binop op="times">
                <ct:SymbRef blkIdRef="p" symbIdRef="Q"/>
                <math:Binop op="minus">
                  <math:Binop op="divide">
                    <ct:SymbRef symbIdRef="A2"/>
                    <ct:SymbRef blkIdRef="p" symbIdRef="V2"/>
                  </math:Binop>
                  <math:Binop op="divide">
                    <ct:SymbRef symbIdRef="A1"/>
                    <ct:SymbRef blkIdRef="p" symbIdRef="V1"/>
                  </math:Binop>
                </math:Binop>
              </math:Binop>
            </math:Binop>
          </math:Equation>
        </ct:Assign>
        <ct:IndependentVariable>
          <ct:SymbRef symbIdRef="t"/>
        </ct:IndependentVariable>
        <ct:InitialCondition>
          <ct:InitialValue>
            <ct:Assign>
              <ct:SymbRef blkIdRef="p" symbIdRef="A1_init"/>
            </ct:Assign>
          </ct:InitialValue>
        </ct:InitialCondition>
      </ct:DerivativeVariable>
      <!-- A2' (ODE) -->
      <ct:DerivativeVariable symbId="A2" symbolType="real">
        <ct:Assign>
          <math:Equation>
            <math:Binop op="times">
              <math:Uniop op="minus">
                <ct:SymbRef blkIdRef="p" symbIdRef="Q"/>
              </math:Uniop>
              <math:Binop op="minus">
                <math:Binop op="divide">
                  <ct:SymbRef symbIdRef="A2"/>
                  <ct:SymbRef blkIdRef="p" symbIdRef="V2"/>
                </math:Binop>
                <math:Binop op="divide">
                  <ct:SymbRef symbIdRef="A1"/>
                  <ct:SymbRef blkIdRef="p" symbIdRef="V1"/>
                </math:Binop>
              </math:Binop>
            </math:Binop>
          </math:Equation>
        </ct:Assign>
        <ct:IndependentVariable>
          <ct:SymbRef symbIdRef="t"/>
        </ct:IndependentVariable>
        <ct:InitialCondition>
          <ct:InitialValue>
            <ct:Assign>
              <ct:SymbRef blkIdRef="p" symbIdRef="A2_init"/>
            </ct:Assign>
          </ct:InitialValue>
        </ct:InitialCondition>
      </ct:DerivativeVariable>
      <!-- C1 (Variable) -->
      <ct:Variable symbId="C1" symbolType="real">
        <ct:Assign>
          <math:Equation>
            <math:Binop op="divide">
              <ct:SymbRef symbIdRef="A1"/>
              <ct:SymbRef blkIdRef="p" symbIdRef="V1"/>
            </math:Binop>
          </math:Equation>
        </ct:Assign>
      </ct:Variable>
    </StructuralModel>
  </ModelDefinition>
</PharmML>
),$s);

